# Latest release blog post
[[redirects]]
from = "/updates"
to = "https://blog.docksal.io/docksal-1-13-0-release-bf56b64861d3"
status = 302
force = true # Ensure that we always redirect the "from" path
