# Assumes DOCKSAL_STACK=node
version: "2.1"

services:
  cli:
    # Extend the stock cli image (see .docksal/services/cli/Dockerfile)
    image: ${COMPOSE_PROJECT_NAME_SAFE}/cli
    build: services/cli
